require(dplyr)
input <- read.csv("exdata-data-household_power_consumption/household_power_consumption.txt", sep =";", header=TRUE,colClasses="character")
input1 <- tbl_df(input)
input2 <- filter(input1, Date=="1/2/2007" | Date =="2/2/2007")
input3 <- mutate(input2, Date = paste(input2$Date, input2$Time, sep=" "))
input3$Date <- strptime(input3$Date, format = "%d/%m/%Y %H:%M:%S")
png(file="plot2.png",width = 480, height = 480)
plot(input3$Date, as.numeric(input3$Global_active_power), type ="l", xlab="",ylab="Global Active Power(kilowatts)")
dev.off()