require(dplyr)
input <- read.csv("exdata-data-household_power_consumption/household_power_consumption.txt", sep =";", header=TRUE,colClasses="character")
input1 <- tbl_df(input)
input2 <- filter(input1, Date=="1/2/2007" | Date =="2/2/2007")
input4 <- mutate(input2, Date = paste(input2$Date, input2$Time, sep=" "))
input4$Date <- strptime(input4$Date, format = "%d/%m/%Y %H:%M:%S")
png(file="plot3.png",width = 480, height = 480)
with(input4,plot(input4$Date,input4$Sub_metering_1, type="n", ylab = "Energy sub metering"))
with(input4,points(input4$Date,input4$Sub_metering_1,col="black",type="l"))
with(input4,points(input4$Date,input4$Sub_metering_2,col="red",type="l"))
with(input4,points(input4$Date,input4$Sub_metering_3,col="blue",type="l"))
dev.off()