require(dplyr)
png(file="plot4.png",width = 480, height = 480)
par(mfrow=c(2,2), mar=c(4,4,2,2))
input <- read.csv("exdata-data-household_power_consumption/household_power_consumption.txt", sep =";", header=TRUE,colClasses="character")
input1 <- tbl_df(input)
input2 <- filter(input1, Date=="1/2/2007" | Date =="2/2/2007")
input5 <- mutate(input2, Date = paste(input2$Date, input2$Time, sep=" "))
input5$Date <- strptime(input5$Date, format = "%d/%m/%Y %H:%M:%S")
plot(input5$Date, as.numeric(input5$Global_active_power),ylab = "Global Active Power",type="l" , xlab="")
plot(input5$Date,input5$Voltage, type="l", ylab="Voltage",xlab="datetime")
with(input5,plot(input5$Date,input5$Sub_metering_1, type="l", ylab = "Energy sub metering",xlab=""))
with(input5,points(input5$Date,input5$Sub_metering_1,col="black",type="l"))
with(input5,points(input5$Date,input5$Sub_metering_2,col="red",type="l"))
with(input5,points(input5$Date,input5$Sub_metering_3,col="blue",type="l"))
plot(input5$Date,input5$Global_reactive_power,xlab = "datetime", type="l", ylab="Global_reactive_power")
dev.off()